### ISSUE TITLE
Test scripts should refference `python2`

### ISSUE THREAD

**Issue by Foxboron** [Fjodor42/jottalib-ng#9]
The scripts used for testing should probably reference `python2` explicitly until full python3 compatibility is reached.
https://github.com/Fjodor42/jottalib-ng/tree/master/tests

**Comment by Fjodor42** [comment]
Incidentally, tests pass for me, using both 2 and 3, when run like this:

`PYTHONPATH=/home/sune/src/Fjodor42/jottalib-ng/src python -m pytest -rsx tests`

`PYTHONPATH=/home/sune/src/Fjodor42/jottalib-ng/src python3 -m pytest -rsx tests`

Dunno if `PYTHONPATH=./src`... would work, but if so a `run_tests.sh` reflecting that and the above could be added?

**Comment by Foxboron** [comment]
pytest doesnt utilize the scripts provided. It's a 3 parth system. Running pytest, `./tests/fusetest.sh` and then `./tests/clitest.sh`. Unless we can confirm they work on both versions they should probably be fixed to use python2.

**Comment by Fjodor42** [comment]
To be honest, I don't have the full understanding of all testing scripts.

What I seem to have gathered is that pytest utilises the ones starting with test_, so those are the ones I have concentrated on, and those seem to run fine with python 3, at least at my end.

My apologies for the confusion.

Would it be possible for you, in any way, to see if there are tests in the other scripts that aren't in the ones mentioned and report back?

If there aren't, I think they should be removed in favour of the pytest ones, and if there are, they should be ported to the pytest ones (or new pytest files) - what do you think?
